USE [master]
GO
/****** Object:  Database [Mibase]    Script Date: 10/10/2025 4:01:41 AM ******/
CREATE DATABASE [Mibase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Mibase', FILENAME = N'C:\BasesSQL\Mibase.mdf' , SIZE = 10240KB , MAXSIZE = 1048576KB , FILEGROWTH = 131072KB ), 
 FILEGROUP [Secundario] 
( NAME = N'Mibase_Data1', FILENAME = N'C:\BasesSQL\Mibase_Data1.ndf' , SIZE = 10240KB , MAXSIZE = 1048576KB , FILEGROWTH = 131072KB ),
( NAME = N'Mibase_Data2', FILENAME = N'C:\BasesSQL\Mibase_Data2.ndf' , SIZE = 10240KB , MAXSIZE = 1048576KB , FILEGROWTH = 131072KB ), 
 FILEGROUP [Terciario] 
( NAME = N'MiBase_Data3', FILENAME = N'C:\BasesSQL\Mibase_Data3.ndf' , SIZE = 512000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'Mibase_Log', FILENAME = N'C:\logSQL\Mibase_Log.ldf' , SIZE = 10240KB , MAXSIZE = 1048576KB , FILEGROWTH = 131072KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Mibase] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Mibase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Mibase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Mibase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Mibase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Mibase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Mibase] SET ARITHABORT OFF 
GO
ALTER DATABASE [Mibase] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Mibase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Mibase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Mibase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Mibase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Mibase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Mibase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Mibase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Mibase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Mibase] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Mibase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Mibase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Mibase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Mibase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Mibase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Mibase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Mibase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Mibase] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Mibase] SET  MULTI_USER 
GO
ALTER DATABASE [Mibase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Mibase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Mibase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Mibase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Mibase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Mibase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Mibase] SET QUERY_STORE = ON
GO
ALTER DATABASE [Mibase] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Mibase]
GO
/****** Object:  User [usrVentas]    Script Date: 10/10/2025 4:01:41 AM ******/
CREATE USER [usrVentas] FOR LOGIN [usrVentas] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Schema [Finanzas]    Script Date: 10/10/2025 4:01:41 AM ******/
CREATE SCHEMA [Finanzas]
GO
/****** Object:  Schema [Inventario]    Script Date: 10/10/2025 4:01:41 AM ******/
CREATE SCHEMA [Inventario]
GO
/****** Object:  Schema [Ventas]    Script Date: 10/10/2025 4:01:41 AM ******/
CREATE SCHEMA [Ventas]
GO
/****** Object:  Table [Ventas].[Clientes]    Script Date: 10/10/2025 4:01:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Ventas].[Clientes](
	[ClientesID] [int] NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](150) NULL,
	[Activo] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ClientesID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [Ventas].[vwClientesActivos]    Script Date: 10/10/2025 4:01:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [Ventas].[vwClientesActivos]
AS
SELECT ClientesID, Nombre, Email
FROM Ventas.Clientes
WHERE Activo = 1;
GO
/****** Object:  Table [dbo].[Tabla1]    Script Date: 10/10/2025 4:01:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tabla1](
	[id] [int] NOT NULL,
	[nombre] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tabla2]    Script Date: 10/10/2025 4:01:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tabla2](
	[id] [int] NOT NULL,
	[descripcion] [nvarchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [Secundario]
) ON [Secundario]
GO
/****** Object:  Table [dbo].[Tabla3]    Script Date: 10/10/2025 4:01:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tabla3](
	[id] [int] NOT NULL,
	[valor] [decimal](10, 2) NULL,
 CONSTRAINT [PK_Tabla3] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [Terciario]
) ON [Terciario]
GO
ALTER TABLE [Ventas].[Clientes] ADD  DEFAULT ((1)) FOR [Activo]
GO
USE [master]
GO
ALTER DATABASE [Mibase] SET  READ_WRITE 
GO
